name: gitleak
on: [pull_request, push, workflow_dispatch]
jobs:
  scan:
    - name: Setup Gitleaks
      id: gitleaks
      run: |
        curl -LO "https://github.com/zricethezav/gitleaks/releases/download/v7.2.0/gitleaks-linux-amd64"
        chmod +x gitleaks-linux-amd64
        sudo mv gitleaks-linux-amd64 /usr/local/bin/gitleaks

   - name: Gitleaks Scan
     run: gitleaks detect -v -r ${{github.workspace}}
