name: "Validate Gradle Wrapper"
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
  workflow_dispatch: 

jobs:
  validation:
    name: "Validation"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.3.4

      - name: GitLeaks Scan
        run: |
          curl -sfL https://github.com/zricethezav/gitleaks/releases/download/v7.7.0/gitleaks-linux-amd64 -o gitleaks
          chmod +x gitleaks
          if [ ! -x ./gitleaks ]; then
            echo "GitLeaks binary is not executable."
            exit 1
          fi
          mkdir -p $RUNNER_TOOL_CACHE
          mv gitleaks $RUNNER_TOOL_CACHE
          # Run GitLeaks scan on the repository
          gitleaks --path . --verbose
        if: always()
