name: Security Check
on:
  push:
    branches:
      - 'master'

jobs:
  Docker:
    name: Docker Check
    runs-on: ci
    steps:
      - name: Checkout code
        uses: actions/checkout@v3    
  
      - name: Scan dockerfile for Policy violation github
        uses: aquasecurity/trivy-action@master
        with:
          scan-type: 'config'
          hide-progress: false
          format: 'table'
          ignore-unfixed: true

      - name: Scan dockerfile for Policy violation sarif
        uses: aquasecurity/trivy-action@master
        with:
          scan-type: 'config'
          hide-progress: false
          format: 'sarif'
          output: 'trivy-results.sarif'
          ignore-unfixed: true  

      - name: Parse SARIF file
        uses: Miragon/sarif-report-parse@v1.0.3
        with:
          sarif-file: trivy-results.sarif

      - name: Run Trivy in GitHub SBOM mode and submit results to Dependency Graph
        uses: aquasecurity/trivy-action@master
        with:
          scan-type: 'config'
          format: 'github'
          output: 'dependency-results.sbom.json'
          image-ref: '.'
          github-pat: ${{ secrets.GITHUB_TOKEN }}

      - name: Publish Trivy SARIF Results
        uses: actions/upload-artifact@v3
        with:
          name: trivy-report
          path: trivy-results.sarif
